version: '3.8'
services:
  cleanmaster-app:
    image: cleanmaster-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: CleanMaster
      MYSQL_USER: CleanMaster
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge