version: '3.8'
services:

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: CleanMaster
      MYSQL_USER: CleanMaster
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/CleanMaster
      SPRING_DATASOURCE_USERNAME: CleanMaster
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
